### ISSUE TITLE
inconsistent exe name

### ISSUE THREAD

**Issue by robrich** [marcelklehr/iodist#3]
https://github.com/marcelklehr/iodist/blob/master/lib/iodist.js#L93 shows the file as node.exe, https://github.com/marcelklehr/iodist/blob/master/lib/iodist.js#L101 shows the file as iojs.exe.  After I install it, use can't find it.  Which is the appropriate exe name?

**Comment by marcelklehr** [comment]
Sorry, I haven't been able to test thoroughly yet. Thank you.
